/*
 *  UCF COP3330 Summer 2021 Assignment 3 Solution
 *  Copyright 2021 Christopher Polanco
 */
 @startuml
'https://plantuml.com/sequence-diagram
!define DARKRED
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

class websiteGenerator {
- site : String
- author : String
- cssFolders : String
- jsFolders : String
--
+ websiteGenerator (setAuthor : String, setSite : String, setJavascript : boolean, setCSS : boolean)
+ main (args : String[]) : void
+ callSite () : String
+ callAuthor () : String
+ callJavascript () : boolean
+ setAuthor (scanString : String) : void
+ getAuthor () : String
+ setJavascript (javaScript : boolean) : void
+ getJavaScript () : boolean
+ getSite () : String
+ getJavaScript () : boolean
+ callCSS () : boolean
+ setCSS (scanner : boolean) : void
- makeDir () : void
}

websiteGeneratorTest <|-- websiteGenerator

class websiteGeneratorTest {
- siteAuthor : String
- siteName : String
--
~ should_pass_if_jsFolder_created() : void
~ should_pass_if_cssFolder_created () : void
}

@enduml